*Writing code to practice **exploratory data analysis (EDA)** covering the  foundational EDA practices*

In [52]:
# downloading a dataset from kaggle
import kagglehub
path=kagglehub.dataset_download("lokatiraghuvaran/cafe-sales-dirty-and-clean-dataset")

Using Colab cache for faster access to the 'cafe-sales-dirty-and-clean-dataset' dataset.

In [53]:
print(path)

/kaggle/input/cafe-sales-dirty-and-clean-dataset

In [54]:
# fixing the complex nested directory structure issue by os.walk()
import os
import pandas as pd
for root, _, filenames in os.walk(path):
    for filename in filenames:
        print(f"\nfiles:{filenames}")
        print(os.path.join(root, filename))

print(f"\nroot dir path: {root}")

files:['cafe_sales_cleaned.csv']
/kaggle/input/cafe-sales-dirty-and-clean-dataset/data/processed/cafe_sales_cleaned.csv

files:['cafe_sales_dirty.csv']
/kaggle/input/cafe-sales-dirty-and-clean-dataset/data/raw/cafe_sales_dirty.csv

root dir path: /kaggle/input/cafe-sales-dirty-and-clean-dataset/data/raw

In [55]:
# inspecting the cleaned dataset
clean_path=os.path.join(path, 'data', 'processed', 'cafe_sales_cleaned.csv')
df=pd.read_csv(clean_path)

print(f"loaded data from:{clean_path}")
print(f"shape:{df.shape}")
display(df.head())

loaded data from:/kaggle/input/cafe-sales-dirty-and-clean-dataset/data/processed/cafe_sales_cleaned.csv
shape:(9539, 12)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Day of Week,Month,Year
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,Friday,September,2023.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,Tuesday,May,2023.0
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19,4.0,Wednesday,July,2023.0
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27,10.0,Thursday,April,2023.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,Sunday,June,2023.0

In [56]:
# exploring and cleaning practice on raw dataset
dirt_path=os.path.join(path, 'data', 'raw', 'cafe_sales_dirty.csv')
df=pd.read_csv(dirt_path)

print(f"loaded data from:{dirt_path}")
print(f"shape:{df.shape}")
display(df.head())

loaded data from:/kaggle/input/cafe-sales-dirty-and-clean-dataset/data/raw/cafe_sales_dirty.csv
shape:(10000, 8)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [57]:
# getting basic information on rows, columns and types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
None

In [58]:
# getting statistical summary on all numeric& categorical columns
print(df.describe(include='all'))

       Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827
unique          10000     10        7              8          19
top       TXN_9226047  Juice        5            3.0         6.0
freq                1   1171     2013           2429         979

        Payment Method  Location Transaction Date
count             7421      6735             9841
unique               5         4              368
top     Digital Wallet  Takeaway          UNKNOWN
freq              2291      3022              159

In [59]:
# we know there are null values, summing up them here
print(df.isnull().sum())

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [60]:
# we check if any duplicates, print their count
"""
- df.duplicated() returns a bool Series list marking True for duplicated rows,
passing it inside [] pandas uses this Series to select rows.

- Where, the True marked rows from df.duplicated() gets filtered by using
df[df.duplicated()] from the original df and returns a new DataFrame
containing only the duplicate rows.

- This common pandas technique is called boolean indexing.
"""

duplicate_rows=df[df.duplicated()]
print(f"number of duplicate rows: {duplicate_rows.shape[0]}")

if not duplicate_rows.empty:
    print("duplicate rows:")
    display(duplicate_rows)
else:
    print("\nno duplicates.")

number of duplicate rows: 0

no duplicates.

In [61]:
# check for duplicate column names
duplicate_columns=df.columns[df.columns.duplicated()]

if not duplicate_columns.empty:
    print(f"duplicate columns: {list(duplicate_columns)}")
else:
    print("no duplicate columns.")

no duplicate columns.